development:
  adapter: postgresql
  encoding: unicode
  database: tyrannosaurustechwebsite_development
  pool: 5
  username: 
  password:
  host: localhost
  port: 5432

test:
  adapter: postgresql
  encoding: unicode
  database: tyrannosaurustechwebsite_test
  pool: 5
  username: 
  password:
  host: localhost
  port: 5432


